### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by shakeelmohamed** [shakeelmohamed/monokai-best#2]
- JSON
- HTML
- JS
- Python
- CSS

**Comment by shakeelmohamed** [comment]
can just grab these from the color sublime website like so:
![capturfiles_8](https://cloud.githubusercontent.com/assets/1480063/7552051/70ad537a-f655-11e4-8ca2-8181a7bc795d.png)

**Comment by talaniz** [comment]
So you just need someone to take screenshots of this theme using examples in JSON, HTML, etc? If so, I can probably do this...

**Comment by shakeelmohamed** [comment]
@talaniz yes please! You can put them in a `screenshots` folder

**Comment by shakeelmohamed** [comment]
All done thanks to @StefanJanssen95 in #4
